#!/bin/sh
cd ~/
mkdir -p setup/
cd setup

sudo apt-get update
sudo apt-get install build-essential libgtk2.0-dev libssl-dev xsltproc libxml2-dev libcap-dev
#sudo apt-get install gcc-multilib g++-multilib libc6-i386 libc6-dev-i386 libssl-dev:i386 libxml2-dev:i386
sudo apt-get install libtool
sudo apt-get install git-core
#yes
sudo apt-get install python

cd $HOME
git clone http://github.com/bengardner/uncrustify.git
cd uncrustify
git checkout uncrustify-0.61
sudo apt-get install autoconf
autoreconf
./configure
sudo make install
#yes

sudo apt-get install doxygen
#yes
sudo apt-get install graphviz
#yes
wget http://www.gaia-gis.it/gaia-sins/freexl-1.0.2.tar.gz
tar -xvf freexl-1.0.2.tar.gz
cd freexl-1.0.2
./configure --prefix=/usr
sudo make install

#libtool install prerequired
wget https://github.com/OSGeo/proj.4/archive/master.zip
unzip proj.4-master.zip
cd proj.4-master
sh autogen.sh
./configure --prefix=/usr
sudo make install

wget http://gaia-gis.it/gaia-sins/readosm-1.0.0e.tar.gz
tar -xvf readosm-1.0.0e.tar.gz
cd readosm-1.0.0e
./configure --prefix=/usr
sudo make install

wget http://download.osgeo.org/geos/geos-3.5.0.tar.bz2
tar -xvf geos-3.5.0.tar.bz2
cd geos-3.5.0
./configure --prefix=/usr
sudo make install

### DBs download
wget http://www.sqlite.org/2016/sqlite-autoconf-3140100.tar.gz
tar -xvf sqlite-autoconf-3140100.tar.gz
cd sqlite-autoconf-3140100
./configure --prefix=/usr
sudo make install
wget http://www.gaia-gis.it/gaia-sins/libspatialite-4.3.0a.tar.gz
tar -xvf libspatialite-4.3.0a.tar.gz
cd libspatilalite-4.3.0a
./configure --prefix=/usr
sudo make install
wget http://www.gaia-gis.it/gaia-sins/spatialite-tools-4.3.0.tar.gz
tar -xvf spatialite-tools-4.3.0.tar.gz
./configure --prefix=/usr
sudo make install

