#!/bin/sh
sudo apt-get install g++
sudo apt-get install libg11-mesa-dev libglu1-mesa-dev
sudo apt-get install build-essential

sudo apt-add-repository ppa:ubuntu-sdk-team/ppa   
sudo apt-get update

sudo apt-get install qtdeclarative4-dev

cd /tmp
gunzip qt-everywhere-opensource-src-5.8.0.tar.gz
tar xvf qt-everywhere-opensource-src-5.8.0.tar

cd /tmp/qt-everywhere-opensource-src-5.8.0
./configure

make

make install

cd ~/
#sudo vi .profile
#PATH = /usr/local/Qt-5.8.0/bin:$PATH
#export PATH
#sudo vi .login
#setenv PATH /usr/local/Qt-5.8.0/bin:$PATH



#chmod a+x qt-opensource-linux-x64-5.6.2.run
#./qt-opensource-linux-x86-5.6.2.run

#sudo apt-get install qtdeclarative5-dev
